apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.relayer.name }}{{ .Values.index }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "relayers-service.labels" $ | nindent 4 }}

spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.secret.projectID }}
  data:
  - key:  {{ .Values.secret.key }}-{{ .Values.index }}
    name: {{ .Values.secret.config.name }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.relayer.name }}-passphrase
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.secret.projectID }}
  data:
  - key:  {{ .Values.secret.passphrase.key }}
    name: {{ .Values.secret.passphrase.name }}
    version: {{ .Values.secret.passphrase.version }}
    property: {{ .Values.secret.passphrase.name }}
---