apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}{{ .Values.index }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "relayers-service.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ .Values.relayer.name }}
    component: {{ .Values.relayer.name }}{{ .Values.index }}
  ports:
    - port: 3000
      targetPort: {{ .Values.relayer.port }}