name: "relayer-server"

relayer:
  name: "relayer-server"
  port: "3000"

namespace: "sdk-prod"

secret:
  projectID: biconomy-prod
  
  passphrase:
    key: sdk-prod-relayer-node-service-passphrase
    name: CONFIG_PASSPHRASE
    version: latest

ingress:
  host: sdk-relayer.prod.biconomy.io
